apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.name" . }}-notification-token
  namespace: {{ include "orchestrator.namespace" . }}
  annotations:
    {{- include "orchestrator.argocd-syncwave" . | nindent 4 }}
type: opaque
stringData:
  NOTIFICATIONS_BEARER_TOKEN: {{ .Values.notification.token }}
  BACKSTAGE_NOTIFICATIONS_URL: {{ .Values.notification.url }}
