apiVersion: v1
kind: Service
metadata:
  name: insurances
  namespace: {{ .Release.Namespace }}
  labels:
    app: insurances
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: insurances