apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  {{ include "redhat-developer-hub-application.name" . }}
  namespace: {{ .Values.gitops.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: ""
    namespace: {{ include "redhat-developer-hub-application.namespace" . }}
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 15
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
  sources:
    - repoURL: {{ .Values.helm.repo }}
      chart: {{ .Values.helm.chart }}
      targetRevision: {{ .Values.helm.version }}
      helm:
        valueFiles:
        - $values/{{ .Values.helm.values.git.path }}
    - repoURL: 'https://{{ .Values.helm.values.git.host }}/{{ .Values.helm.values.git.group }}/{{ .Values.helm.values.git.repo }}.git'
      targetRevision: {{ .Values.helm.values.git.revision }}
      ref: values
