{{- if eq .Values.persistence.mode "persistent" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sonataflow-postgresql.name" . }}
  labels:
    {{- include "sonataflow-postgresql.labels" . | nindent 4 }}
  annotations:
    {{- include "sonataflow-postgresql.argocd-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}