apiVersion: batch/v1
kind: Job
metadata:
  name: parasol-images
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: skopeo
        command:
          - /bin/bash
          - '-c'
          - |
            skopeo copy --dest-creds {{ .Values.registry.username }}:{{ .Values.registry.password }} {{ include "parasol.store.source.image" . }} {{ include "parasol.store.image" . }}
            skopeo copy --dest-creds {{ .Values.registry.username }}:{{ .Values.registry.password }} {{ include "parasol.web.source.image" . }} {{ include "parasol.web.image" . }}
        image: registry.redhat.io/rhel9/skopeo:9.4
      restartPolicy: Never
