apiVersion: batch/v1
kind: Job
metadata:
  name: parasol-web
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: parasol-web
        command:
          - /bin/bash
          - '-c'
          - |
            set -x
            ansible-playbook -i localhost /scripts/playbook.yaml
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
          - mountPath: /scripts
            name: parasol-web-vol
      restartPolicy: Never
      volumes:
      - name: parasol-web-vol
        configMap:
          name: parasol-web-manifests