---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "rhtas.name" . }}-operator
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}