{{- if .Values.serverless.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.serverless.subscription.name }}
  namespace: {{ .Values.serverless.namespace }}
  annotations:
    {{- include "orchestrator-operator.argocd-syncwave" (dict "syncwave" .Values.argocd.syncwaves.serverless "argocd" .Values.argocd) | nindent 4 }}
spec:
  channel: {{ .Values.serverless.subscription.channel }}
  installPlanApproval: {{ .Values.serverless.subscription.installPlanApproval }}
  name: {{ .Values.serverless.subscription.name }}
  source: {{ .Values.serverless.subscription.source }}
  sourceNamespace: {{ .Values.serverless.subscription.sourceNamespace }}
{{- end }}
{{- if .Values.serverlessLogic.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.serverlessLogic.subscription.name }}
  namespace: {{ .Values.serverlessLogic.namespace }}
  annotations:
    {{- include "orchestrator-operator.argocd-syncwave" (dict "syncwave" .Values.argocd.syncwaves.serverlessLogic "argocd" .Values.argocd) | nindent 4 }}
spec:
  channel: {{ .Values.serverlessLogic.subscription.channel }}
  installPlanApproval: {{ .Values.serverlessLogic.subscription.installPlanApproval }}
  name: {{ .Values.serverlessLogic.subscription.name }}
  source: {{ .Values.serverlessLogic.subscription.source }}
  sourceNamespace: {{ .Values.serverlessLogic.subscription.sourceNamespace }}
{{- end }}
