---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quay-registry.name" . }}-config-bundle
  labels:
    {{- include "quay-registry.labels" . | nindent 4 }}
  annotations:
    {{- include "quay-registry.quay.argocd-syncwave" . | nindent 4 }}
stringData:
  config.yaml: |-
    REGISTRY_TITLE: {{ .Values.quay.displayName }}
    SERVER_HOSTNAME: {{ .Values.quay.host }}
    EXTERNAL_TLS_TERMINATION: {{ .Values.quay.tls }}
    {{- if .Values.quay.configureAdmin }}
    SUPER_USERS:
    - {{ .Values.quay.adminUser }}
    FEATURE_USER_INITIALIZE: {{ .Values.quay.userInitialize }}
    {{- end }}
