apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quay-registry.name" . }}-config
  labels:
    {{- include "quay-registry.labels" . | nindent 4 }}
  annotations:
    {{- include "quay-registry.config.argocd-syncwave" . | nindent 4 }}  
