apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quay-registry.name" . }}-noobaa
  labels:
    {{- include "quay-registry.labels" . | nindent 4 }}
  annotations:
    {{- include "quay-registry.noobaa.argocd-syncwave" . | nindent 4 }}  
