apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: rhdh-role
          secretRef:
            key: token
            name: {{ .Values.vault.name }}-auth-secret
            namespace: {{ .Values.vault.auth.namespace }}
          serviceAccountRef:
            name: {{ .Values.vault.name }}-auth
            namespace: {{ .Values.vault.auth.namespace }}
      path: kv
      server: 'http://{{ .Values.vault.name }}.{{ .Values.vault.namespace }}:8200'
      version: v2