apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-client
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth-client
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: secrets/keycloak/client-secret
        property: clientId
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: secrets/keycloak/client-secret
        property: clientSecret
