{{- if and (default false .Values.orchestrator.enabled) (not (default true .Values.upstream.postgresql.serviceBindings.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redhat-developer-hub-prereqs.name" . }}-postgresql-svcbind-postgres
  namespace: {{ include "redhat-developer-hub-prereqs.name" . }}
  labels:
    app.kubernetes.io/instance: {{ include "redhat-developer-hub-prereqs.name" . }}
    app.kubernetes.io/name: postgresql
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
type: servicebinding.io/postgresql
stringData:
  provider: "bitnami"
  type: "postgresql"
  host: "{{ include "redhat-developer-hub-prereqs.name" . }}-postgresql"
  port: "5432"
  username: "{{ .Values.upstream.postgresql.auth.username | default "postgres" }}"
  database: "{{ .Values.upstream.postgresql.auth.database | default "postgres" }}"
  password: "{{ .Values.upstream.postgresql.auth.password }}"
  uri: "postgresql://{{ .Values.upstream.postgresql.auth.username | default "postgres" }}:{{ .Values.upstream.postgresql.auth.password }}@{{ include "redhat-developer-hub-prereqs.name" . }}-postgresql:5432/{{ .Values.upstream.postgresql.auth.database | default "postgres" }}"
{{- end }}
