kind: Secret
apiVersion: v1
metadata:
  name: dynamic-plugins-npmrc
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  .npmrc: registry=https://npm.registry.redhat.com  
type: Opaque
