kind: Secret
apiVersion: v1
metadata:
  name: backstage-orchestrator-token
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  orchestrator-token: {{ randAlphaNum 24 }}