apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.orchestrator.name "namespace" .Values.argocd.namespace "syncWave" "3") }}
spec:
  destination:
    namespace: {{ .Values.orchestrator.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: orchestrator
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        orchestrator:
          backstage:
            namespace: {{ .Values.orchestrator.namespace }}
            backend:
              url: {{ .Values.orchestrator.backstage.backend.url }}
          openshift:
            url: {{ .Values.orchestrator.openshift.url }}
          gitlab:
            url: {{ .Values.orchestrator.gitlab.url }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
