apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.rhdh.name "namespace" .Values.argocd.namespace "syncWave" "2") }}
spec:
  destination:
    namespace: {{ .Values.rhdh.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: redhat-developer-hub
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        redhat-developer-hub-prereqs:
          vault:
            namespace: {{ .Values.vault.namespace }}
            name: {{ .Values.vault.name }}
          backstage:
            postgresql:
              password: {{ .Values.vault.secrets.rhdh.postgresqlPassword | quote }}
        redhat-developer-hub-config-template:
          gitlab:
            rootPassword: {{ .Values.rhdh.configTemplate.gitlab.rootPassword | quote }}
            host: {{ .Values.rhdh.configTemplate.gitlab.host }}
          backstage:
            host: {{ .Values.rhdh.configTemplate.backstage.host }}
          keycloak:
            host: {{ .Values.rhdh.configTemplate.keycloak.host }}
            realm: {{ .Values.rhdh.configTemplate.keycloak.realm }}
            loginRealm: {{ .Values.rhdh.configTemplate.keycloak.loginRealm }}
            clientId: {{ .Values.rhdh.configTemplate.keycloak.clientId }}
            clientSecret: {{ .Values.rhdh.configTemplate.keycloak.clientSecret | quote }}
          gitops:
            host: {{ .Values.rhdh.configTemplate.gitops.host }}
          kubernetes:
            api: {{ .Values.rhdh.configTemplate.kubernetes.api }}
          cluster:
            subdomain: {{ .Values.rhdh.configTemplate.cluster.subdomain }}
        redhat-developer-hub-application:
          gitops:
            namespace: {{ .Values.rhdh.application.gitops.namespace }}
          helm:
            version: {{ .Values.rhdh.application.helm.version }}
            values:
              git:
                host: {{ .Values.rhdh.application.helm.values.git.host }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 15
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
