---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: {{ include "devspaces-instance.name" . }}
  namespace: {{ include "devspaces-instance.namespace" . }}
  annotations:
    {{- include "devspaces-instance.argocd-syncwave" . | nindent 4 }}
spec:
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email
      debug: false
      logLevel: INFO
    dashboard: {}
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: {{ .Values.devEnvironments.startTimeoutSeconds }}
    secondsOfRunBeforeIdling: {{ .Values.devEnvironments.secondsOfRunBeforeIdling }}
    maxNumberOfWorkspacesPerUser: {{ .Values.devEnvironments.maxNumberOfWorkspacesPerUser }}
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: false
    defaultEditor: {{ .Values.devEnvironments.defaultEditor }}
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-user
  gitServices:
    gitlab:
      - secretName: gitlab-oauth-config
        endpoint: https://{{ .Values.gitlab.host }}
  networking:
    auth:
      identityProviderURL: {{ .Values.oidc.identityProviderURL }}
      oAuthClientName: {{ .Values.oidc.oAuthClientName }}
      oAuthSecret: {{ .Values.oidc.oAuthSecret }}
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        oAuthProxy:
          cookieExpireSeconds: 300
        deployment:
          containers:
            - name: oauth-proxy
              env:
                - name: OAUTH2_PROXY_PROVIDER
                  value: oidc
                - name: OAUTH2_PROXY_OIDC_ISSUER_URL
                  value: {{ .Values.oidc.identityProviderURL }}
                - name: OAUTH2_PROXY_CLIENT_ID
                  value: {{ .Values.oidc.oAuthClientName }}
                - name: OAUTH2_PROXY_CLIENT_SECRET
                  value: {{ .Values.oidc.oAuthSecret }}
                - name: OAUTH2_PROXY_SCOPE
                  value: openid email profile
                - name: OAUTH2_PROXY_EMAIL_DOMAINS
                  value: "*"
                - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
                  value: "true"
                - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
                  value: "true"
                - name: OAUTH2_PROXY_BACKEND_LOGOUT_URL
                  value: "{{ .Values.oidc.identityProviderURL }}/protocol/openid-connect/logout?id_token_hint={id_token}"
