{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ticket-manager.serviceAccountName" . }}
  labels:
    {{- include "ticket-manager.labels" . | nindent 4 }}
  annotations:
    {{- include "ticket-manager.argocd-syncwave" . | nindent 4 }}
{{- end }}
